-- Выполните целиком в Supabase → SQL Editor.

create table if not exists public.places (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  city text not null check (city in ('minsk','brest','grodno')),
  category text not null check (category in ('history','beautiful','park','food','coffee')),
  address text not null default '',
  lat double precision not null,
  lon double precision not null,
  source_url text,
  note text not null default '',
  vegan boolean not null default false,
  constraint vegan_only_food_coffee check (vegan = false or category in ('food','coffee'))
);

alter table public.places enable row level security;

drop policy if exists "public read places" on public.places;
create policy "public read places"
on public.places for select
to anon
using (true);

drop policy if exists "public insert places" on public.places;
create policy "public insert places"
on public.places for insert
to anon
with check (
  city in ('minsk','brest','grodno')
  and category in ('history','beautiful','park','food','coffee')
  and (vegan = false or category in ('food','coffee'))
);

-- Специально НЕ разрешаем update/delete через публичный ключ.
-- Если ошиблась при добавлении, строку можно поправить вручную в Supabase Table Editor.

-- Начальные точки Гродно:
insert into public.places (name,city,category,address,lat,lon,note,vegan)
values
('Старый замок', 'grodno', 'history', 'Замковая гора, Гродно', 53.677, 23.823, 'Королевская резиденция над Неманом — история и сильные виды на реку.', false),
('Новый замок', 'grodno', 'history', 'ул. Замковая, 20', 53.6763, 23.8253, 'Королевский дворец XVIII века напротив Старого замка.', false),
('Смотровая «Крыша мира»', 'grodno', 'beautiful', 'ул. Советская, 18', 53.68235, 23.83155, 'Центральная смотровая с крышами старого города.', false),
('Коложский парк', 'grodno', 'park', 'район Коложи', 53.67841, 23.81859, 'Зелёный склон над Неманом вокруг Коложской церкви.', false),
('Парк Жилибера', 'grodno', 'park', 'центр Гродно', 53.6852, 23.8379, 'Центральный парк для короткой паузы между городскими точками.', false),
('The Cult', 'grodno', 'food', 'ул. Виленская, 37', 53.685167, 23.825747, 'Вариант для полноценного ужина в исторической части.', false),
('Бистро «Семолина»', 'grodno', 'food', 'ул. Советская, 7', 53.679919, 23.8304, 'Удобно встроить прямо в прогулку по пешеходной Советской.', false),
('Поляна City', 'grodno', 'food', 'ул. Советская, 25', 53.681531, 23.831739, 'Еда прямо в центре без отдельного крюка.', false),
('ТЕПЛО', 'grodno', 'coffee', 'ул. Большая Троицкая, 37', 53.680591, 23.827355, 'Небольшая кофейня в квартале Большой Троицкой.', false),
('Джезва', 'grodno', 'coffee', 'ул. Советская, 5', 53.679637, 23.830131, 'Кофе в джезве, в том числе приготовление на песке.', false),
('Бар «Урбанист»', 'grodno', 'food', 'ул. Мостовая, 31', 53.676975, 23.828594, 'Вечерняя барная точка в центре.', false),
('Наше место', 'grodno', 'coffee', 'ул. Дарвина, 24', 53.6713, 23.8233, 'Кофе плюс вид с высокого берега Немана на старый город.', false),
('Проходная', 'grodno', 'coffee', 'ул. Мостовая, 31', 53.676975, 23.828594, 'Спешелти-кофейня в центре.', false),
('Крепкий Белый', 'grodno', 'coffee', 'ул. Замковая, 10', 53.6781, 23.8274, 'Кофейня рядом с замками.', true),
('Справа', 'grodno', 'coffee', 'ул. Мостовая, 31', 53.676975, 23.828594, 'Кафе в центральном квартале.', false),
('Лесопарк Пышки', 'grodno', 'park', 'урочище Пышки', 53.7138, 23.7941, 'Большой лесной массив для длинной прогулки.', false);
